### PR TITLE
fix: fix pipeline errors with updated enviroment

### PR DESCRIPTION
**Pull request by Ming-Yan**
- update `test_env.yml`
- update `README.md` for the environment setup and plotting script example
- change root file name to avoid `coffea` bug
- add global flags for `runner.py` 
- put btag SFs under `self.isCorr` flag

### CODE REVIEW

**Comment by andrzejnovak** [comment]
Hi @Ming-Yan, I am not sure I follow. The PR seems to change quite a few things and have a number of commits, are all these changes related to the pipeline fix?

**Comment by demuller** [comment]
There is also one test failing due to missing psutil: https://github.com/cms-btv-pog/BTVNanoCommissioning/actions/runs/3190652124/jobs/5206043621#step:9:18

concerning the commits: some of them are again 5 months old, so I don't understand why they appear here tbh

**Comment by andrzejnovak** [comment]
@demuller just to clarify for security reasons the tests are always run against the config already in `master` so a change to the workflow/processor does get tested correctly, but changes to the `yml` configs won't be reflected in the jobs that run for the PR

**Comment by demuller** [comment]
> @demuller just to clarify for security reasons the tests are always run against the config already in `master` so a change to the workflow/processor does get tested correctly, but changes to the `yml` configs won't be reflected in the jobs that run for the PR

True, I forgot, so that failed test is an expected one

**Comment by demuller** [comment]
> Hi @Ming-Yan, I am not sure I follow. The PR seems to change quite a few things and have a number of commits, are all these changes related to the pipeline fix?

One is referring to a recent issue in coffea [here](https://github.com/CoffeaTeam/coffea/issues/727), which will be fixed centrally in the coffea framework with a new release on Friday

The other thing is that two flags recently introduced by the last PR (`--isJERC` and `--isCorr`) are added to runner.py, so they can be adjusted directly per command line when executing runner.py

So yeah, the PR title only refers to the CI pipeline update, but more stuff actually happened

**Pull request closed without merging**
