### PR TITLE
add the cross-section info  

### PR DESCRIPTION
**Pull request by Ming-Yan**
put the xsection info in the plotting code

### CODE REVIEW

**Comment by andrzejnovak** [comment]
@Ming-Yan thanks, any chance you could factor it out into a module?

I am guessing the signature is sth like ` scale(<dict/hist-in>, xs_dict, sample_axis) -> <hist-out>` so it should be easy to have this in a module called `plotting` or sth.

**Comment by Ming-Yan** [comment]
I think I could do something similar like this, then we can get scales through the module.
This could be either put in the code or scale out as a module in a python file

`def scale_xs(events,lumi):

# events2 = output2['sumw']

    #xsection in pb
    xs_dict = {
        'QCD_Pt-15to20_MuEnrichedPt5_TuneCP5_13TeV_pythia8':3820000,
        'QCD_Pt-20to30_MuEnrichedPt5_TuneCP5_13TeV_pythia8':2960000,
        'QCD_Pt-30to50_MuEnrichedPt5_TuneCP5_13TeV_pythia8':1652471,
        'QCD_Pt-50to80_MuEnrichedPt5_TuneCP5_13TeV_pythia8':437504,
        'QCD_Pt-80to120_MuEnrichedPt5_TuneCP5_13TeV_pythia8':106033,
        'QCD_Pt-120to170_MuEnrichedPt5_TuneCP5_13TeV_pythia8':24720,
        'QCD_Pt-170to300_MuEnrichedPt5_TuneCP5_13TeV_pythia8':8654,
        'QCD_Pt-300to470_MuEnrichedPt5_TuneCP5_13TeV_pythia8':797,
        'QCD_Pt-470to600_MuEnrichedPt5_TuneCP5_13TeV_pythia8':79,
        'QCD_Pt-600to800_MuEnrichedPt5_TuneCP5_13TeV_pythia8':25,
        'QCD_Pt-800to1000_MuEnrichedPt5_TuneCP5_13TeV_pythia8':4.7,
        'QCD_Pt-1000toInf_MuEnrichedPt5_TuneCP5_13TeV_pythia8':1.6,
        'WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8':61524,
        'DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8':6024,
        'TTToHadronic_TuneCP5_13TeV-powheg-pythia8':313.9,
        'TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8':72.1,
        'TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8':300.9,
        'ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8':35.6,
        'ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8':35.6,
        'ST_t-channel_top_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8':136.02,
        'ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8':80.95,
        'ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8':3.74,
        'ST_s-channel_4f_hadronicDecays_TuneCP5_13TeV-amcatnlo-pythia8':11.24,
        "WW_TuneCP5_13TeV-pythia8":63.21,
        "WZ_TuneCP5_13TeV-pythia8":47.13,
        "ZZ_TuneCP5_13TeV-pythia8":16.523   
    }
    scales={}

    for key in events:
        if type(key) != str or key=="Data": continue
        scales[key]=xs_dict[key]*lumi/events[key]
    return scales
`
We could the do some simple things like
`
events = output['sumw']
lumi = 4319 #in pb
scales=scale_xs(events,lumi) # get weight through this
`

**Comment by andrzejnovak** [comment]
That's the easy part right? There should be a function to apply these to `coffea.hist` objects. Would be nice if the the xs info was a separate file in a json format. Possibly you could even query https://cms-gen-dev.cern.ch/xsdb/ automatically

**Comment by Ming-Yan** [comment]
update the xsection reader into python module by doing `scale_xs(coffea.hist,luminosity,output['sumw']) `, the modules are in `xs_scaler.py` and I stored the xsection info in `xsection.json`.
But the info in  [](https://cms-gen-dev.cern.ch/xsdb/) is not complete correct, for example the ttbar leptonic decay, hadronic decay and semileptonic decay is same xs...

**Comment by andrzejnovak** [comment]
@Ming-Yan scaler looks ok to me, are you sure you want to commit the notebooks as well? they don't generate a good diff so it's hard to keep track of the changes

**Comment by Ming-Yan** [comment]
remove the jupyter notebook, leave the original one

**Comment by andrzejnovak** [comment]
alright, looks good to me

**Pull request merged**
